// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

public final class Grpc {
  private Grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wjq_netty_protobuffer_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wjq_netty_protobuffer_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wjq_netty_protobuffer_StudentReponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wjq_netty_protobuffer_StudentReponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wjq_netty_protobuffer_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wjq_netty_protobuffer_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wjq_netty_protobuffer_HelloReponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wjq_netty_protobuffer_HelloReponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wjq_netty_protobuffer_StudentReponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wjq_netty_protobuffer_StudentReponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wjq_netty_protobuffer_StreamReponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wjq_netty_protobuffer_StreamReponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\022\031com.wjq.netty.protobuffer\"" +
      "\033\n\rStreamRequest\022\n\n\002id\030\001 \001(\005\"9\n\016StudentR" +
      "eponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004cit" +
      "y\030\003 \001(\t\"\035\n\014HelloRequest\022\r\n\005greet\030\001 \001(\t\"\035" +
      "\n\014HelloReponse\022\r\n\005reply\030\001 \001(\t\"W\n\022Student" +
      "ReponseList\022A\n\016studentReponse\030\001 \003(\0132).co" +
      "m.wjq.netty.protobuffer.StudentReponse\"%" +
      "\n\rStreamReponse\022\024\n\014reponse_info\030\001 \001(\t2\260\003" +
      "\n\014HelloService\022^\n\010SayHello\022\'.com.wjq.net" +
      "ty.protobuffer.HelloRequest\032\'.com.wjq.ne" +
      "tty.protobuffer.HelloReponse\"\000\022e\n\nGetStu" +
      "dent\022(.com.wjq.netty.protobuffer.StreamR" +
      "equest\032).com.wjq.netty.protobuffer.Stude" +
      "ntReponse\"\0000\001\022j\n\013GetStudents\022(.com.wjq.n" +
      "etty.protobuffer.StreamRequest\032-.com.wjq" +
      ".netty.protobuffer.StudentReponseList\"\000(" +
      "\001\022m\n\021GetStudentsStream\022(.com.wjq.netty.p" +
      "rotobuffer.StreamRequest\032(.com.wjq.netty" +
      ".protobuffer.StreamReponse\"\000(\0010\001B\035\n\031com." +
      "wjq.netty.protobufferP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_wjq_netty_protobuffer_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wjq_netty_protobuffer_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wjq_netty_protobuffer_StreamRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_wjq_netty_protobuffer_StudentReponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wjq_netty_protobuffer_StudentReponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wjq_netty_protobuffer_StudentReponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_wjq_netty_protobuffer_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wjq_netty_protobuffer_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wjq_netty_protobuffer_HelloRequest_descriptor,
        new java.lang.String[] { "Greet", });
    internal_static_com_wjq_netty_protobuffer_HelloReponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_wjq_netty_protobuffer_HelloReponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wjq_netty_protobuffer_HelloReponse_descriptor,
        new java.lang.String[] { "Reply", });
    internal_static_com_wjq_netty_protobuffer_StudentReponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_wjq_netty_protobuffer_StudentReponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wjq_netty_protobuffer_StudentReponseList_descriptor,
        new java.lang.String[] { "StudentReponse", });
    internal_static_com_wjq_netty_protobuffer_StreamReponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_wjq_netty_protobuffer_StreamReponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wjq_netty_protobuffer_StreamReponse_descriptor,
        new java.lang.String[] { "ReponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
