// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

public interface HelloReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wjq.netty.protobuffer.HelloReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
