// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wjq.netty.protobuffer.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greet = 1;</code>
   * @return The greet.
   */
  java.lang.String getGreet();
  /**
   * <code>string greet = 1;</code>
   * @return The bytes for greet.
   */
  com.google.protobuf.ByteString
      getGreetBytes();
}
