// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wjq.netty.protobuffer.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
