// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

public interface StreamReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wjq.netty.protobuffer.StreamReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reponse_info = 1;</code>
   * @return The reponseInfo.
   */
  java.lang.String getReponseInfo();
  /**
   * <code>string reponse_info = 1;</code>
   * @return The bytes for reponseInfo.
   */
  com.google.protobuf.ByteString
      getReponseInfoBytes();
}
