// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

/**
 * Protobuf type {@code com.wjq.netty.protobuffer.StreamReponse}
 */
public  final class StreamReponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.wjq.netty.protobuffer.StreamReponse)
    StreamReponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamReponse.newBuilder() to construct.
  private StreamReponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamReponse() {
    reponseInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamReponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamReponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reponseInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wjq.netty.protobuffer.Grpc.internal_static_com_wjq_netty_protobuffer_StreamReponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wjq.netty.protobuffer.Grpc.internal_static_com_wjq_netty_protobuffer_StreamReponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wjq.netty.protobuffer.StreamReponse.class, com.wjq.netty.protobuffer.StreamReponse.Builder.class);
  }

  public static final int REPONSE_INFO_FIELD_NUMBER = 1;
  private volatile java.lang.Object reponseInfo_;
  /**
   * <code>string reponse_info = 1;</code>
   * @return The reponseInfo.
   */
  public java.lang.String getReponseInfo() {
    java.lang.Object ref = reponseInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reponseInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string reponse_info = 1;</code>
   * @return The bytes for reponseInfo.
   */
  public com.google.protobuf.ByteString
      getReponseInfoBytes() {
    java.lang.Object ref = reponseInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reponseInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReponseInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reponseInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReponseInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reponseInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wjq.netty.protobuffer.StreamReponse)) {
      return super.equals(obj);
    }
    com.wjq.netty.protobuffer.StreamReponse other = (com.wjq.netty.protobuffer.StreamReponse) obj;

    if (!getReponseInfo()
        .equals(other.getReponseInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPONSE_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getReponseInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wjq.netty.protobuffer.StreamReponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wjq.netty.protobuffer.StreamReponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.wjq.netty.protobuffer.StreamReponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.wjq.netty.protobuffer.StreamReponse)
      com.wjq.netty.protobuffer.StreamReponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjq.netty.protobuffer.Grpc.internal_static_com_wjq_netty_protobuffer_StreamReponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjq.netty.protobuffer.Grpc.internal_static_com_wjq_netty_protobuffer_StreamReponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjq.netty.protobuffer.StreamReponse.class, com.wjq.netty.protobuffer.StreamReponse.Builder.class);
    }

    // Construct using com.wjq.netty.protobuffer.StreamReponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reponseInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wjq.netty.protobuffer.Grpc.internal_static_com_wjq_netty_protobuffer_StreamReponse_descriptor;
    }

    @java.lang.Override
    public com.wjq.netty.protobuffer.StreamReponse getDefaultInstanceForType() {
      return com.wjq.netty.protobuffer.StreamReponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wjq.netty.protobuffer.StreamReponse build() {
      com.wjq.netty.protobuffer.StreamReponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wjq.netty.protobuffer.StreamReponse buildPartial() {
      com.wjq.netty.protobuffer.StreamReponse result = new com.wjq.netty.protobuffer.StreamReponse(this);
      result.reponseInfo_ = reponseInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wjq.netty.protobuffer.StreamReponse) {
        return mergeFrom((com.wjq.netty.protobuffer.StreamReponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wjq.netty.protobuffer.StreamReponse other) {
      if (other == com.wjq.netty.protobuffer.StreamReponse.getDefaultInstance()) return this;
      if (!other.getReponseInfo().isEmpty()) {
        reponseInfo_ = other.reponseInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wjq.netty.protobuffer.StreamReponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wjq.netty.protobuffer.StreamReponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object reponseInfo_ = "";
    /**
     * <code>string reponse_info = 1;</code>
     * @return The reponseInfo.
     */
    public java.lang.String getReponseInfo() {
      java.lang.Object ref = reponseInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reponseInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reponse_info = 1;</code>
     * @return The bytes for reponseInfo.
     */
    public com.google.protobuf.ByteString
        getReponseInfoBytes() {
      java.lang.Object ref = reponseInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reponseInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reponse_info = 1;</code>
     * @param value The reponseInfo to set.
     * @return This builder for chaining.
     */
    public Builder setReponseInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reponseInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reponse_info = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReponseInfo() {
      
      reponseInfo_ = getDefaultInstance().getReponseInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string reponse_info = 1;</code>
     * @param value The bytes for reponseInfo to set.
     * @return This builder for chaining.
     */
    public Builder setReponseInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reponseInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.wjq.netty.protobuffer.StreamReponse)
  }

  // @@protoc_insertion_point(class_scope:com.wjq.netty.protobuffer.StreamReponse)
  private static final com.wjq.netty.protobuffer.StreamReponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wjq.netty.protobuffer.StreamReponse();
  }

  public static com.wjq.netty.protobuffer.StreamReponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamReponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamReponse>() {
    @java.lang.Override
    public StreamReponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamReponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamReponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamReponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wjq.netty.protobuffer.StreamReponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

