// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.wjq.netty.protobuffer;

public interface StudentReponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wjq.netty.protobuffer.StudentReponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.wjq.netty.protobuffer.StudentReponse studentReponse = 1;</code>
   */
  java.util.List<com.wjq.netty.protobuffer.StudentReponse> 
      getStudentReponseList();
  /**
   * <code>repeated .com.wjq.netty.protobuffer.StudentReponse studentReponse = 1;</code>
   */
  com.wjq.netty.protobuffer.StudentReponse getStudentReponse(int index);
  /**
   * <code>repeated .com.wjq.netty.protobuffer.StudentReponse studentReponse = 1;</code>
   */
  int getStudentReponseCount();
  /**
   * <code>repeated .com.wjq.netty.protobuffer.StudentReponse studentReponse = 1;</code>
   */
  java.util.List<? extends com.wjq.netty.protobuffer.StudentReponseOrBuilder> 
      getStudentReponseOrBuilderList();
  /**
   * <code>repeated .com.wjq.netty.protobuffer.StudentReponse studentReponse = 1;</code>
   */
  com.wjq.netty.protobuffer.StudentReponseOrBuilder getStudentReponseOrBuilder(
      int index);
}
